server:
  port: 9095

spring:
  application:
    name: 241CC341SpringMSDemo01UsuarioD
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cpo7e6l6l47c73aai91g-a.oregon-postgres.render.com/sisvita_fv8f
    username: grupo1
    password: UzM3qfPAlL3e8uU4lEJghJCOPRrDVbEQ
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka